name: Build and Release Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # Step 3: Restore dependencies with correct path
      - name: Install dependencies
        run: dotnet restore ./YourProjectFolder/YourProject.sln

      # Step 4: Build the app
      - name: Build the app
        run: dotnet build ./YourProjectFolder/YourProject.sln --configuration Release

      # Step 5: Publish the app
      - name: Publish the app
        run: dotnet publish ./YourProjectFolder/YourProject.sln -c Release -o ./publish

      # Step 6: Upload Release to GitHub
      - name: Upload Release to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: iCloudNotes
          path: ./publish

      # Step 7: Create a Release
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/**
          tag_name: v1.0.0
          release_name: "iCloudNotes v1.0.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
