name: Build and Release Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code from the repo
      - name: Check out the code
        uses: actions/checkout@v3

      # Step 2: Set up .NET environment (Adjust the version if needed)
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Update this to your .NET version

      # Step 3: Restore the project dependencies
      - name: Install dependencies
        run: dotnet restore

      # Step 4: Build the app in Release mode
      - name: Build the app
        run: dotnet build --configuration Release

      # Step 5: Publish the app to a folder
      - name: Publish the app
        run: dotnet publish -c Release -o ./publish

      # Step 6: Upload the build as an artifact
      - name: Upload Release to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: iCloudNotes
          path: ./publish

      # Step 7: Create a GitHub release and upload the build
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/**
          tag_name: v1.0.0  # Change version as needed
          release_name: "iCloudNotes v1.0.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
